#!/usr/bin/env bash

alias prj='"$($(find $HOME/bin -maxdepth 1 -type f -executable | fzf --prompt="Select a project: "))"'

choice=$(find $HOME/bin -maxdepth 1 -type f -executable | fzf --prompt="Select a project: ")

if [[ -n "$choice" ]] then
	"$choice" 
else 
	echo "No project selected"
	exit 1
fi


